#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the raw capacity of Ceph 
# Expects to be run on a ceph client with access to the filesystem
# N.B. This script needs to be run with SUDO by the nagios user

lowthresh=$1
highthresh=$2

# See if we were passed any variables, and set thresholds if not
if [ "$lowthresh" == ""  ] ; then
  lowthresh=85
fi

if [ "$highthresh" == "" ] ; then
  highthresh=95
fi

# Check monitor is present and executable
if [ ! -x /usr/bin/ceph ] ; then
   echo "Cannot execute Ceph monitor - is it installed?"
   exit 3
fi

tmpfile=/var/tmp/cephcheck.$$

# the command to run to check the service
/usr/bin/ceph df | grep -A 2 GLOBAL | tail -1 > $tmpfile 2>&1

foundtot=`cat $tmpfile | awk '{print $1}'`
foundfree=`cat $tmpfile | awk '{print $2}'`
foundpc=`cat $tmpfile | awk '{print $4}' | cut -d. -f1`
rm -f $tmpfile

if [ $foundpc -ge $highthresh ] ; then
   echo "Ceph raw usage at ${foundpc}% ($foundfree free of $foundtot)"
   exit 2
elif [ $foundpc -ge $lowthresh ] ; then
   echo "Ceph raw usage at ${foundpc}% ($foundfree free of $foundtot)"
   exit 1
elif [ $foundpc -lt $lowthresh ] ; then
   echo "Ceph raw usage at ${foundpc}% ($foundfree free of $foundtot)"
   exit 0
else
   echo "Unable to detect raw Ceph usage"
   exit 3
fi

# Should not reach here
exit 3

