#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

if [ ! -x /usr/sbin/quotaon ] ; then
   echo "No quotaon command - is it installed?"
   exit 3
fi

# Script to check if user quotas are enabled on this server
quotaon -p -a | grep users > /tmp/checkquota.$$ 2>&1

if [ `grep -c "is on" /tmp/checkquota.$$` -ne 2 ] ; then
   if [ `grep -c "is off" /tmp/checkquota.$$` -eq 2 ] ; then
      echo "User quotas configured but not turned on"
      rm -rf /tmp/checkquota.$$
      exit 1
   else
      echo "No user quotas configured"
      rm -rf /tmp/checkquota.$$
      exit 0
   fi
else
   echo "Quotas enabled on user filesystem"
   rm -rf /tmp/checkquota.$$
   exit 0
fi 

# should not reach here
exit 3


