#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of a HP hpacucli volume
# Volume ID is passed as parameter 1
# Adapter card is passed as parameter 2
# N.B. This script needs to be run with SUDO by the nagios user

binary=/usr/sbin/hpssacli
# Check monitor is present and executable
if [ ! -x $binary ] ; then
   echo "Cannot execute HP disk monitor - is it installed?"
   exit 3
fi

vol=$1
card=$2

# Check that sg kernel module is loaded
if [ `lsmod | egrep "^sg " | wc -l` -lt 1 ] ; then
   modprobe sg > /etc/null 2>&1
fi

# the command to run to check the service
checkcommand=`$binary controller slot=$card logicaldrive $vol show | grep Status | head -1`

if [ `echo $checkcommand | grep -c OK | awk '{print $1}'` -lt 1 ] ; then
   echo "System disk RAID volume warning: `echo $checkcommand | sed 's?\t? ?g'`"
   exit 1
else
   echo "System disk RAID volume OK"
   exit 0
fi

