#!/bin/bash
################################################################################
# (c) Copyright 2007-2015 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of HP health flag on iLO via IPMI

# set ecc-check spool directory
checkdir=/var/spool/nagios/ipmi-check

# Check that ECC output files are available
[[ -d $checkdir ]] || exit 3

# Check that we've been passed a parameter
remote=$1
if [ ! $remote ] ; then
   echo "No node name passed to check"
   exit 3
fi

# check we have output for this node
if [ ! -f $checkdir/$remote.ipmi.out ] ; then
   echo "No log information found for $remote"
   exit 3
fi

# the command to run to check the service
checkcommand=`egrep "Health LED" $checkdir/$remote.ipmi.out`

if [ `echo $checkcommand | egrep -c "OEM Event = 0001h" | awk '{print $1}'` -lt 1 ] ; then
   echo "HP iLO reporting health problem"
   exit 1
else
   echo "HP iLO health ok"
   exit 0
fi

