#!/bin/bash
################################################################################
# (c) Copyright 2007-2011 Alces Software Ltd                                   #
#                                                                              #
# HPC Cluster Toolkit                                                          #
#                                                                              #
# This file/package is part of the HPC Cluster Toolkit                         #
#                                                                              #
# This is free software: you can redistribute it and/or modify it under        #
# the terms of the GNU Affero General Public License as published by the Free  #
# Software Foundation, either version 3 of the License, or (at your option)    #
# any later version.                                                           #
#                                                                              #
# This file is distributed in the hope that it will be useful, but WITHOUT     #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or        #
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License #
# for more details.                                                            #
#                                                                              #
# You should have received a copy of the GNU Affero General Public License     #
# along with this product.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
# For more information on Alces Software, please visit:                        #
# http://www.alces-software.org/                                               #
#                                                                              #
################################################################################

# Script to check the status of Ceph OSD daemons
# Expected number of Ceph OSDs passed as first parameter
# N.B. This script needs to be run with SUDO by the nagios user

# Check monitor is present and executable
if [ ! -x /usr/bin/ceph ] ; then
   echo "Cannot execute Ceph monitor - is it installed?"
   exit 3
fi

osds=$1
if [ "$osds" == "" ] ; then
   echo "Pass number of expected OSDs as first parameter"
   exit 1
fi

tmpfile=/var/tmp/cephcheck.$$

# the command to run to check the service
/usr/bin/ceph osd tree > $tmpfile

foundosds=`grep osd $tmpfile | wc -l`
uposds=`grep osd $tmpfile | grep -c up`
rm -f $tmpfile

if [ $foundosds -ne $osds ] ; then
   echo "Found $foundosds OSD(s) active - expected $osds"
   exit 1
elif [ $uposds -ne $osds ] ; then
   downosds=`expr $osds - $uposds`
   echo "$downosds of $osds OSD(s) currently down"
   exit 1
else
   echo "Found $uposds OSD(s) running"
   exit 0
fi

